live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[font]
size = 15
normal = { family = "Noto Sans Mono", style = "Regular" }

[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be99'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
