live_config_reload = true
import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[font]
size = 24
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }

[colors.primary]
background = "#000000"
