live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[font]
size = 15
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }

[colors.primary]
background = "#000000"
