import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }

[font]
size = 12.5
normal = { family = "Jet Brains Mono Nerd Font", style = "Regular" }
