live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true
padding = { x = 4, y = 4 }
startup_mode = "Maximized"

[font]
size = 14
normal = { family = "FiraCode Nerd Font", style = "Regular" }
