live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
blur = true
padding = { x = 4, y = 4 }
startup_mode = "Maximized"

[font]
size = 19
normal = { family = "Fira Mono", style = "Regular" }
